### ISSUE TITLE
About aws gameday server error 500

### ISSUE THREAD

**Issue by 1558861030** [rumd3x/aws-gameday-unicorn#2]
Hello, I'm a student studying AWS. We took part in an AWS game a few days ago, but we encountered some problems when we took part in the activity. When the server was just running, it was normal. But after the organizer carried out some operations, my server made a 500 error. I tried a lot of ways to solve this problem, but I didn't solve it. Then I found it here, and I hope I can solve it. What's wrong with me

**Comment by rumd3x** [comment]
That's actually the whole point of the challenge. The software is faulty on purpose (it only responds correctly to like 5 to 10 requests, taking longer and longer to respond each request, until it finally responds only errors and needs to be rebooted), and you need to overcome this handicap by using infrastructure resources: monitoring, scaling, cacheing, etc. On my solution I keep the app really stable and cheap by using a cloudfront to cache requests and a single ec2 instance, inside it I have a docker stack, using a nginx container as a custom load balancer and reverse proxy to communicate with multiple instances of the faulty application, which also has a healthcheck and is configured to autoheal.

**Comment by 1558861030** [comment]
> 您好，我是一名学习AWS的学生。几天前，我们参加了一个AWS游戏，但在参加活动时遇到了一些问题。当服务器刚刚运行时，这是正常的。但是在组织者执行了一些操作之后，我的服务器出现了500错误。我尝试了很多方法来解决此问题，但没有解决。然后我在这里找到了它，希望可以解决。我怎么了

**Comment by 1558861030** [comment]
In my mind, cloudfront It's a service for caching static files. I don't know if the program has been modified by the organizer of the game. At that time, we had a hash get method to request our server. Our server seems to reply to another hash. When hash returns correctly, we can score. Otherwise, points will be deducted. I don't think it's necessary to use cloudfront it's just hash for transmission, because it's all dynamic data processing, the data returned is the different every time. Maybe I don't know enough about cloudfront service. Please help me to answer it. Thank you

**Comment by rumd3x** [comment]
Well, cloudfront is not only for static files. The game actually make a lot of repeated requests that will output the same hash, and the faster your response, the more points you make. When cacheing you will respond in a couple milliseconds, against 10 to 30 seconds it takes for the software to calculate it every time, and as I stated, the application takes longer every time and needs to be rebooted every couple requests, so cacheing instead of wasting compute resources is a good idea.
